// Gegenereerd door pnpm tokens:build. Niet met de hand aanpassen.

export type Tokenlaag = 'primitief' | 'semantisch' | 'componenten';

export interface Token {
  readonly naam: string;
  readonly pad: string;
  readonly laag: Tokenlaag;
  readonly waarde: string;
}

export const tokens: readonly Token[] = [
  { naam: 'k-beweging-duur-snel', pad: 'beweging.duur.snel', laag: 'primitief', waarde: "150ms" },
  { naam: 'k-beweging-duur-basis', pad: 'beweging.duur.basis', laag: 'primitief', waarde: "300ms" },
  { naam: 'k-beweging-duur-traag', pad: 'beweging.duur.traag', laag: 'primitief', waarde: "600ms" },
  { naam: 'k-beweging-duur-trager', pad: 'beweging.duur.trager', laag: 'primitief', waarde: "900ms" },
  { naam: 'k-beweging-duur-filmisch', pad: 'beweging.duur.filmisch', laag: 'primitief', waarde: "1200ms" },
  { naam: 'k-beweging-duur-hero', pad: 'beweging.duur.hero', laag: 'primitief', waarde: "1600ms" },
  { naam: 'k-beweging-duur-ambient', pad: 'beweging.duur.ambient', laag: 'primitief', waarde: "90000ms" },
  { naam: 'k-beweging-curve-uit-quint', pad: 'beweging.curve.uit-quint', laag: 'primitief', waarde: "cubic-bezier(0.22, 1, 0.36, 1)" },
  { naam: 'k-beweging-curve-uit-expo', pad: 'beweging.curve.uit-expo', laag: 'primitief', waarde: "cubic-bezier(0.16, 1, 0.3, 1)" },
  { naam: 'k-beweging-curve-in-uit-quart', pad: 'beweging.curve.in-uit-quart', laag: 'primitief', waarde: "cubic-bezier(0.76, 0, 0.24, 1)" },
  { naam: 'k-beweging-curve-ambient', pad: 'beweging.curve.ambient', laag: 'primitief', waarde: "cubic-bezier(0.37, 0, 0.63, 1)" },
  { naam: 'k-beweging-trap-snel', pad: 'beweging.trap.snel', laag: 'primitief', waarde: "60ms" },
  { naam: 'k-beweging-trap-basis', pad: 'beweging.trap.basis', laag: 'primitief', waarde: "90ms" },
  { naam: 'k-beweging-trap-traag', pad: 'beweging.trap.traag', laag: 'primitief', waarde: "140ms" },
  { naam: 'k-beweging-afstand-sm', pad: 'beweging.afstand.sm', laag: 'primitief', waarde: "8px" },
  { naam: 'k-beweging-afstand-md', pad: 'beweging.afstand.md', laag: 'primitief', waarde: "16px" },
  { naam: 'k-beweging-afstand-lg', pad: 'beweging.afstand.lg', laag: 'primitief', waarde: "32px" },
  { naam: 'k-beweging-afstand-masker', pad: 'beweging.afstand.masker', laag: 'primitief', waarde: "110%" },
  { naam: 'k-beweging-schaal-hover', pad: 'beweging.schaal.hover', laag: 'primitief', waarde: "1.03" },
  { naam: 'k-beweging-schaal-onthul', pad: 'beweging.schaal.onthul', laag: 'primitief', waarde: "1.08" },
  { naam: 'k-beweging-parallax-hoeveelheid', pad: 'beweging.parallax.hoeveelheid', laag: 'primitief', waarde: "6%" },
  { naam: 'k-kleur-papier-0', pad: 'kleur.papier.0', laag: 'primitief', waarde: "#ffffff" },
  { naam: 'k-kleur-papier-50', pad: 'kleur.papier.50', laag: 'primitief', waarde: "#faf9f7" },
  { naam: 'k-kleur-papier-100', pad: 'kleur.papier.100', laag: 'primitief', waarde: "#f3f1ec" },
  { naam: 'k-kleur-lijn-200', pad: 'kleur.lijn.200', laag: 'primitief', waarde: "#e3e0d9" },
  { naam: 'k-kleur-steen-400', pad: 'kleur.steen.400', laag: 'primitief', waarde: "#9b968d" },
  { naam: 'k-kleur-inkt-700', pad: 'kleur.inkt.700', laag: 'primitief', waarde: "#4a4844" },
  { naam: 'k-kleur-inkt-900', pad: 'kleur.inkt.900', laag: 'primitief', waarde: "#1b1a18" },
  { naam: 'k-kleur-inkt-1000', pad: 'kleur.inkt.1000', laag: 'primitief', waarde: "#000000" },
  { naam: 'k-kleur-hout-es-200', pad: 'kleur.hout.es.200', laag: 'primitief', waarde: "#e7decf" },
  { naam: 'k-kleur-hout-eik-400', pad: 'kleur.hout.eik.400', laag: 'primitief', waarde: "#c7a67a" },
  { naam: 'k-kleur-hout-noten-700', pad: 'kleur.hout.noten.700', laag: 'primitief', waarde: "#6a4931" },
  { naam: 'k-kleur-fout-600', pad: 'kleur.fout.600', laag: 'primitief', waarde: "#a23a29" },
  { naam: 'k-letter-familie-kop', pad: 'letter.familie.kop', laag: 'primitief', waarde: "'Instrument Sans Variable', 'Kop terugval', system-ui, sans-serif" },
  { naam: 'k-letter-familie-tekst', pad: 'letter.familie.tekst', laag: 'primitief', waarde: "'Work Sans Variable', 'Tekst terugval', system-ui, sans-serif" },
  { naam: 'k-letter-gewicht-licht', pad: 'letter.gewicht.licht', laag: 'primitief', waarde: "300" },
  { naam: 'k-letter-gewicht-normaal', pad: 'letter.gewicht.normaal', laag: 'primitief', waarde: "400" },
  { naam: 'k-letter-gewicht-medium', pad: 'letter.gewicht.medium', laag: 'primitief', waarde: "500" },
  { naam: 'k-letter-grootte-xs', pad: 'letter.grootte.xs', laag: 'primitief', waarde: "0.75rem" },
  { naam: 'k-letter-grootte-sm', pad: 'letter.grootte.sm', laag: 'primitief', waarde: "0.875rem" },
  { naam: 'k-letter-grootte-basis', pad: 'letter.grootte.basis', laag: 'primitief', waarde: "clamp(1rem, 0.97rem + 0.15vw, 1.0625rem)" },
  { naam: 'k-letter-grootte-lg', pad: 'letter.grootte.lg', laag: 'primitief', waarde: "clamp(1.125rem, 1.08rem + 0.2vw, 1.25rem)" },
  { naam: 'k-letter-grootte-xl', pad: 'letter.grootte.xl', laag: 'primitief', waarde: "clamp(1.375rem, 1.3rem + 0.35vw, 1.625rem)" },
  { naam: 'k-letter-grootte-2xl', pad: 'letter.grootte.2xl', laag: 'primitief', waarde: "clamp(1.625rem, 1.48rem + 0.62vw, 2.125rem)" },
  { naam: 'k-letter-grootte-3xl', pad: 'letter.grootte.3xl', laag: 'primitief', waarde: "clamp(2rem, 1.72rem + 1.2vw, 3rem)" },
  { naam: 'k-letter-grootte-4xl', pad: 'letter.grootte.4xl', laag: 'primitief', waarde: "clamp(2.5rem, 1.95rem + 2.3vw, 4.25rem)" },
  { naam: 'k-letter-grootte-display', pad: 'letter.grootte.display', laag: 'primitief', waarde: "clamp(3rem, 1.6rem + 5.8vw, 7.5rem)" },
  { naam: 'k-letter-spatiering-display', pad: 'letter.spatiering.display', laag: 'primitief', waarde: "-0.02em" },
  { naam: 'k-letter-spatiering-kop', pad: 'letter.spatiering.kop', laag: 'primitief', waarde: "-0.01em" },
  { naam: 'k-letter-spatiering-tekst', pad: 'letter.spatiering.tekst', laag: 'primitief', waarde: "0" },
  { naam: 'k-letter-spatiering-kapitaal', pad: 'letter.spatiering.kapitaal', laag: 'primitief', waarde: "0.08em" },
  { naam: 'k-letter-regelhoogte-display', pad: 'letter.regelhoogte.display', laag: 'primitief', waarde: "0.95" },
  { naam: 'k-letter-regelhoogte-kop', pad: 'letter.regelhoogte.kop', laag: 'primitief', waarde: "1.12" },
  { naam: 'k-letter-regelhoogte-tekst', pad: 'letter.regelhoogte.tekst', laag: 'primitief', waarde: "1.6" },
  { naam: 'k-ruimte-1', pad: 'ruimte.1', laag: 'primitief', waarde: "0.25rem" },
  { naam: 'k-ruimte-2', pad: 'ruimte.2', laag: 'primitief', waarde: "0.5rem" },
  { naam: 'k-ruimte-3', pad: 'ruimte.3', laag: 'primitief', waarde: "0.75rem" },
  { naam: 'k-ruimte-4', pad: 'ruimte.4', laag: 'primitief', waarde: "1rem" },
  { naam: 'k-ruimte-5', pad: 'ruimte.5', laag: 'primitief', waarde: "1.25rem" },
  { naam: 'k-ruimte-6', pad: 'ruimte.6', laag: 'primitief', waarde: "1.5rem" },
  { naam: 'k-ruimte-8', pad: 'ruimte.8', laag: 'primitief', waarde: "2rem" },
  { naam: 'k-ruimte-10', pad: 'ruimte.10', laag: 'primitief', waarde: "2.5rem" },
  { naam: 'k-ruimte-12', pad: 'ruimte.12', laag: 'primitief', waarde: "3rem" },
  { naam: 'k-ruimte-16', pad: 'ruimte.16', laag: 'primitief', waarde: "4rem" },
  { naam: 'k-ruimte-20', pad: 'ruimte.20', laag: 'primitief', waarde: "5rem" },
  { naam: 'k-ruimte-24', pad: 'ruimte.24', laag: 'primitief', waarde: "6rem" },
  { naam: 'k-ruimte-32', pad: 'ruimte.32', laag: 'primitief', waarde: "8rem" },
  { naam: 'k-ruimte-40', pad: 'ruimte.40', laag: 'primitief', waarde: "10rem" },
  { naam: 'k-ruimte-sectie', pad: 'ruimte.sectie', laag: 'primitief', waarde: "clamp(5rem, 2.8rem + 8vw, 10rem)" },
  { naam: 'k-ruimte-goot', pad: 'ruimte.goot', laag: 'primitief', waarde: "clamp(1.25rem, 0.8rem + 1.8vw, 2.5rem)" },
  { naam: 'k-maat-container-max', pad: 'maat.container-max', laag: 'primitief', waarde: "90rem" },
  { naam: 'k-maat-container-inline', pad: 'maat.container-inline', laag: 'primitief', waarde: "76rem" },
  { naam: 'k-maat-regellengte', pad: 'maat.regellengte', laag: 'primitief', waarde: "68ch" },
  { naam: 'k-radius-geen', pad: 'radius.geen', laag: 'primitief', waarde: "0" },
  { naam: 'k-radius-invoer', pad: 'radius.invoer', laag: 'primitief', waarde: "2px" },
  { naam: 'k-rand-haarlijn', pad: 'rand.haarlijn', laag: 'primitief', waarde: "1px" },
  { naam: 'k-schermbreedte-sm', pad: 'schermbreedte.sm', laag: 'primitief', waarde: "40rem" },
  { naam: 'k-schermbreedte-md', pad: 'schermbreedte.md', laag: 'primitief', waarde: "48rem" },
  { naam: 'k-schermbreedte-lg', pad: 'schermbreedte.lg', laag: 'primitief', waarde: "64rem" },
  { naam: 'k-schermbreedte-xl', pad: 'schermbreedte.xl', laag: 'primitief', waarde: "80rem" },
  { naam: 'k-schermbreedte-2xl', pad: 'schermbreedte.2xl', laag: 'primitief', waarde: "96rem" },
  { naam: 'k-laag-basis', pad: 'laag.basis', laag: 'primitief', waarde: "0" },
  { naam: 'k-laag-kop', pad: 'laag.kop', laag: 'primitief', waarde: "10" },
  { naam: 'k-laag-overlay', pad: 'laag.overlay', laag: 'primitief', waarde: "20" },
  { naam: 'k-laag-modaal', pad: 'laag.modaal', laag: 'primitief', waarde: "30" },
  { naam: 'k-verhouding-liggend', pad: 'verhouding.liggend', laag: 'primitief', waarde: "3 / 2" },
  { naam: 'k-verhouding-staand', pad: 'verhouding.staand', laag: 'primitief', waarde: "4 / 5" },
  { naam: 'k-verhouding-vierkant', pad: 'verhouding.vierkant', laag: 'primitief', waarde: "1 / 1" },
  { naam: 'k-verhouding-breed', pad: 'verhouding.breed', laag: 'primitief', waarde: "16 / 9" },
  { naam: 'beweging-binnenkomst', pad: 'beweging.binnenkomst', laag: 'semantisch', waarde: "600ms cubic-bezier(0.22, 1, 0.36, 1)" },
  { naam: 'beweging-binnenkomst-hero', pad: 'beweging.binnenkomst-hero', laag: 'semantisch', waarde: "1600ms cubic-bezier(0.16, 1, 0.3, 1)" },
  { naam: 'beweging-binnenkomst-beeld', pad: 'beweging.binnenkomst-beeld', laag: 'semantisch', waarde: "1200ms cubic-bezier(0.16, 1, 0.3, 1)" },
  { naam: 'beweging-vertrek', pad: 'beweging.vertrek', laag: 'semantisch', waarde: "300ms cubic-bezier(0.76, 0, 0.24, 1)" },
  { naam: 'beweging-hover', pad: 'beweging.hover', laag: 'semantisch', waarde: "150ms cubic-bezier(0.22, 1, 0.36, 1)" },
  { naam: 'beweging-hover-beeld', pad: 'beweging.hover-beeld', laag: 'semantisch', waarde: "900ms cubic-bezier(0.16, 1, 0.3, 1)" },
  { naam: 'beweging-pagina-uit', pad: 'beweging.pagina-uit', laag: 'semantisch', waarde: "300ms cubic-bezier(0.76, 0, 0.24, 1)" },
  { naam: 'beweging-pagina-in', pad: 'beweging.pagina-in', laag: 'semantisch', waarde: "300ms cubic-bezier(0.22, 1, 0.36, 1)" },
  { naam: 'kleur-achtergrond', pad: 'kleur.achtergrond', laag: 'semantisch', waarde: "#faf9f7" },
  { naam: 'kleur-achtergrond-verhoogd', pad: 'kleur.achtergrond-verhoogd', laag: 'semantisch', waarde: "#ffffff" },
  { naam: 'kleur-achtergrond-tint', pad: 'kleur.achtergrond-tint', laag: 'semantisch', waarde: "#f3f1ec" },
  { naam: 'kleur-voorgrond', pad: 'kleur.voorgrond', laag: 'semantisch', waarde: "#1b1a18" },
  { naam: 'kleur-voorgrond-gedempt', pad: 'kleur.voorgrond-gedempt', laag: 'semantisch', waarde: "#4a4844" },
  { naam: 'kleur-voorgrond-subtiel', pad: 'kleur.voorgrond-subtiel', laag: 'semantisch', waarde: "#9b968d" },
  { naam: 'kleur-voorgrond-invers', pad: 'kleur.voorgrond-invers', laag: 'semantisch', waarde: "#ffffff" },
  { naam: 'kleur-lijn', pad: 'kleur.lijn', laag: 'semantisch', waarde: "#e3e0d9" },
  { naam: 'kleur-lijn-sterk', pad: 'kleur.lijn-sterk', laag: 'semantisch', waarde: "#1b1a18" },
  { naam: 'kleur-accent', pad: 'kleur.accent', laag: 'semantisch', waarde: "#6a4931" },
  { naam: 'kleur-fout', pad: 'kleur.fout', laag: 'semantisch', waarde: "#a23a29" },
  { naam: 'kleur-plaatshouder-eik', pad: 'kleur.plaatshouder.eik', laag: 'semantisch', waarde: "#c7a67a" },
  { naam: 'kleur-plaatshouder-noten', pad: 'kleur.plaatshouder.noten', laag: 'semantisch', waarde: "#6a4931" },
  { naam: 'kleur-plaatshouder-es', pad: 'kleur.plaatshouder.es', laag: 'semantisch', waarde: "#e7decf" },
  { naam: 'kleur-licht-warm', pad: 'kleur.licht.warm', laag: 'semantisch', waarde: "#e7decf" },
  { naam: 'kleur-licht-koel', pad: 'kleur.licht.koel', laag: 'semantisch', waarde: "#e3e0d9" },
  { naam: 'ruimte-sectie', pad: 'ruimte.sectie', laag: 'semantisch', waarde: "clamp(5rem, 2.8rem + 8vw, 10rem)" },
  { naam: 'ruimte-blok', pad: 'ruimte.blok', laag: 'semantisch', waarde: "4rem" },
  { naam: 'ruimte-goot', pad: 'ruimte.goot', laag: 'semantisch', waarde: "clamp(1.25rem, 0.8rem + 1.8vw, 2.5rem)" },
  { naam: 'ruimte-stapel-sm', pad: 'ruimte.stapel.sm', laag: 'semantisch', waarde: "0.5rem" },
  { naam: 'ruimte-stapel-md', pad: 'ruimte.stapel.md', laag: 'semantisch', waarde: "1rem" },
  { naam: 'ruimte-stapel-lg', pad: 'ruimte.stapel.lg', laag: 'semantisch', waarde: "2rem" },
  { naam: 'ruimte-rij-sm', pad: 'ruimte.rij.sm', laag: 'semantisch', waarde: "0.75rem" },
  { naam: 'ruimte-rij-md', pad: 'ruimte.rij.md', laag: 'semantisch', waarde: "1.5rem" },
  { naam: 'ruimte-rij-lg', pad: 'ruimte.rij.lg', laag: 'semantisch', waarde: "3rem" },
  { naam: 'maat-container', pad: 'maat.container', laag: 'semantisch', waarde: "90rem" },
  { naam: 'maat-tekstkolom', pad: 'maat.tekstkolom', laag: 'semantisch', waarde: "76rem" },
  { naam: 'maat-regellengte', pad: 'maat.regellengte', laag: 'semantisch', waarde: "68ch" },
  { naam: 'tekst-display-familie', pad: 'tekst.display.familie', laag: 'semantisch', waarde: "'Instrument Sans Variable', 'Kop terugval', system-ui, sans-serif" },
  { naam: 'tekst-display-grootte', pad: 'tekst.display.grootte', laag: 'semantisch', waarde: "clamp(3rem, 1.6rem + 5.8vw, 7.5rem)" },
  { naam: 'tekst-display-gewicht', pad: 'tekst.display.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-display-regelhoogte', pad: 'tekst.display.regelhoogte', laag: 'semantisch', waarde: "0.95" },
  { naam: 'tekst-display-spatiering', pad: 'tekst.display.spatiering', laag: 'semantisch', waarde: "-0.02em" },
  { naam: 'tekst-display-kort-familie', pad: 'tekst.display-kort.familie', laag: 'semantisch', waarde: "'Instrument Sans Variable', 'Kop terugval', system-ui, sans-serif" },
  { naam: 'tekst-display-kort-grootte', pad: 'tekst.display-kort.grootte', laag: 'semantisch', waarde: "clamp(2rem, 1.72rem + 1.2vw, 3rem)" },
  { naam: 'tekst-display-kort-gewicht', pad: 'tekst.display-kort.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-display-kort-regelhoogte', pad: 'tekst.display-kort.regelhoogte', laag: 'semantisch', waarde: "1.12" },
  { naam: 'tekst-display-kort-spatiering', pad: 'tekst.display-kort.spatiering', laag: 'semantisch', waarde: "-0.01em" },
  { naam: 'tekst-kop1-familie', pad: 'tekst.kop1.familie', laag: 'semantisch', waarde: "'Instrument Sans Variable', 'Kop terugval', system-ui, sans-serif" },
  { naam: 'tekst-kop1-grootte', pad: 'tekst.kop1.grootte', laag: 'semantisch', waarde: "clamp(2.5rem, 1.95rem + 2.3vw, 4.25rem)" },
  { naam: 'tekst-kop1-gewicht', pad: 'tekst.kop1.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-kop1-regelhoogte', pad: 'tekst.kop1.regelhoogte', laag: 'semantisch', waarde: "0.95" },
  { naam: 'tekst-kop1-spatiering', pad: 'tekst.kop1.spatiering', laag: 'semantisch', waarde: "-0.02em" },
  { naam: 'tekst-kop2-familie', pad: 'tekst.kop2.familie', laag: 'semantisch', waarde: "'Instrument Sans Variable', 'Kop terugval', system-ui, sans-serif" },
  { naam: 'tekst-kop2-grootte', pad: 'tekst.kop2.grootte', laag: 'semantisch', waarde: "clamp(2rem, 1.72rem + 1.2vw, 3rem)" },
  { naam: 'tekst-kop2-gewicht', pad: 'tekst.kop2.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-kop2-regelhoogte', pad: 'tekst.kop2.regelhoogte', laag: 'semantisch', waarde: "1.12" },
  { naam: 'tekst-kop2-spatiering', pad: 'tekst.kop2.spatiering', laag: 'semantisch', waarde: "-0.01em" },
  { naam: 'tekst-kop3-familie', pad: 'tekst.kop3.familie', laag: 'semantisch', waarde: "'Instrument Sans Variable', 'Kop terugval', system-ui, sans-serif" },
  { naam: 'tekst-kop3-grootte', pad: 'tekst.kop3.grootte', laag: 'semantisch', waarde: "clamp(1.625rem, 1.48rem + 0.62vw, 2.125rem)" },
  { naam: 'tekst-kop3-gewicht', pad: 'tekst.kop3.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-kop3-regelhoogte', pad: 'tekst.kop3.regelhoogte', laag: 'semantisch', waarde: "1.12" },
  { naam: 'tekst-kop3-spatiering', pad: 'tekst.kop3.spatiering', laag: 'semantisch', waarde: "-0.01em" },
  { naam: 'tekst-kop4-familie', pad: 'tekst.kop4.familie', laag: 'semantisch', waarde: "'Instrument Sans Variable', 'Kop terugval', system-ui, sans-serif" },
  { naam: 'tekst-kop4-grootte', pad: 'tekst.kop4.grootte', laag: 'semantisch', waarde: "clamp(1.375rem, 1.3rem + 0.35vw, 1.625rem)" },
  { naam: 'tekst-kop4-gewicht', pad: 'tekst.kop4.gewicht', laag: 'semantisch', waarde: "500" },
  { naam: 'tekst-kop4-regelhoogte', pad: 'tekst.kop4.regelhoogte', laag: 'semantisch', waarde: "1.12" },
  { naam: 'tekst-kop4-spatiering', pad: 'tekst.kop4.spatiering', laag: 'semantisch', waarde: "0" },
  { naam: 'tekst-intro-familie', pad: 'tekst.intro.familie', laag: 'semantisch', waarde: "'Work Sans Variable', 'Tekst terugval', system-ui, sans-serif" },
  { naam: 'tekst-intro-grootte', pad: 'tekst.intro.grootte', laag: 'semantisch', waarde: "clamp(1.125rem, 1.08rem + 0.2vw, 1.25rem)" },
  { naam: 'tekst-intro-gewicht', pad: 'tekst.intro.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-intro-regelhoogte', pad: 'tekst.intro.regelhoogte', laag: 'semantisch', waarde: "1.6" },
  { naam: 'tekst-intro-spatiering', pad: 'tekst.intro.spatiering', laag: 'semantisch', waarde: "0" },
  { naam: 'tekst-lopend-familie', pad: 'tekst.lopend.familie', laag: 'semantisch', waarde: "'Work Sans Variable', 'Tekst terugval', system-ui, sans-serif" },
  { naam: 'tekst-lopend-grootte', pad: 'tekst.lopend.grootte', laag: 'semantisch', waarde: "clamp(1rem, 0.97rem + 0.15vw, 1.0625rem)" },
  { naam: 'tekst-lopend-gewicht', pad: 'tekst.lopend.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-lopend-regelhoogte', pad: 'tekst.lopend.regelhoogte', laag: 'semantisch', waarde: "1.6" },
  { naam: 'tekst-lopend-spatiering', pad: 'tekst.lopend.spatiering', laag: 'semantisch', waarde: "0" },
  { naam: 'tekst-klein-familie', pad: 'tekst.klein.familie', laag: 'semantisch', waarde: "'Work Sans Variable', 'Tekst terugval', system-ui, sans-serif" },
  { naam: 'tekst-klein-grootte', pad: 'tekst.klein.grootte', laag: 'semantisch', waarde: "0.875rem" },
  { naam: 'tekst-klein-gewicht', pad: 'tekst.klein.gewicht', laag: 'semantisch', waarde: "400" },
  { naam: 'tekst-klein-regelhoogte', pad: 'tekst.klein.regelhoogte', laag: 'semantisch', waarde: "1.6" },
  { naam: 'tekst-klein-spatiering', pad: 'tekst.klein.spatiering', laag: 'semantisch', waarde: "0" },
  { naam: 'tekst-label-familie', pad: 'tekst.label.familie', laag: 'semantisch', waarde: "'Work Sans Variable', 'Tekst terugval', system-ui, sans-serif" },
  { naam: 'tekst-label-grootte', pad: 'tekst.label.grootte', laag: 'semantisch', waarde: "0.75rem" },
  { naam: 'tekst-label-gewicht', pad: 'tekst.label.gewicht', laag: 'semantisch', waarde: "500" },
  { naam: 'tekst-label-regelhoogte', pad: 'tekst.label.regelhoogte', laag: 'semantisch', waarde: "1.12" },
  { naam: 'tekst-label-spatiering', pad: 'tekst.label.spatiering', laag: 'semantisch', waarde: "0.08em" },
  { naam: 'bijschrift-grootte', pad: 'bijschrift.grootte', laag: 'componenten', waarde: "0.75rem" },
  { naam: 'bijschrift-spatiering', pad: 'bijschrift.spatiering', laag: 'componenten', waarde: "0.08em" },
  { naam: 'bijschrift-gewicht', pad: 'bijschrift.gewicht', laag: 'componenten', waarde: "500" },
  { naam: 'bijschrift-voorgrond', pad: 'bijschrift.voorgrond', laag: 'componenten', waarde: "#9b968d" },
  { naam: 'bijschrift-ruimte-boven', pad: 'bijschrift.ruimte-boven', laag: 'componenten', waarde: "0.75rem" },
  { naam: 'plaatshouder-label-grootte', pad: 'plaatshouder.label-grootte', laag: 'componenten', waarde: "0.75rem" },
  { naam: 'plaatshouder-label-voorgrond', pad: 'plaatshouder.label-voorgrond', laag: 'componenten', waarde: "#4a4844" },
  { naam: 'plaatshouder-korrel-dekking', pad: 'plaatshouder.korrel-dekking', laag: 'componenten', waarde: "0.08" },
  { naam: 'binnenkomst-kop', pad: 'binnenkomst.kop', laag: 'componenten', waarde: "0ms" },
  { naam: 'binnenkomst-regel-een', pad: 'binnenkomst.regel-een', laag: 'componenten', waarde: "100ms" },
  { naam: 'binnenkomst-regel-twee', pad: 'binnenkomst.regel-twee', laag: 'componenten', waarde: "190ms" },
  { naam: 'binnenkomst-intro', pad: 'binnenkomst.intro', laag: 'componenten', waarde: "500ms" },
  { naam: 'binnenkomst-lijn', pad: 'binnenkomst.lijn', laag: 'componenten', waarde: "700ms" },
  { naam: 'binnenkomst-blok-een', pad: 'binnenkomst.blok-een', laag: 'componenten', waarde: "800ms" },
  { naam: 'binnenkomst-blok-twee', pad: 'binnenkomst.blok-twee', laag: 'componenten', waarde: "890ms" },
  { naam: 'binnenkomst-blok-drie', pad: 'binnenkomst.blok-drie', laag: 'componenten', waarde: "980ms" },
  { naam: 'binnenkomst-micro', pad: 'binnenkomst.micro', laag: 'componenten', waarde: "1000ms" },
  { naam: 'icoon-maat', pad: 'icoon.maat', laag: 'componenten', waarde: "1rem" },
  { naam: 'icoon-lijndikte', pad: 'icoon.lijndikte', laag: 'componenten', waarde: "1.1" },
  { naam: 'icoon-voorgrond', pad: 'icoon.voorgrond', laag: 'componenten', waarde: "#9b968d" },
  { naam: 'icoon-voorgrond-hover', pad: 'icoon.voorgrond-hover', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'icoon-ruimte', pad: 'icoon.ruimte', laag: 'componenten', waarde: "0.5rem" },
  { naam: 'invoer-hoogte', pad: 'invoer.hoogte', laag: 'componenten', waarde: "3rem" },
  { naam: 'invoer-padding-inline', pad: 'invoer.padding-inline', laag: 'componenten', waarde: "0.75rem" },
  { naam: 'invoer-grootte', pad: 'invoer.grootte', laag: 'componenten', waarde: "1rem" },
  { naam: 'invoer-radius', pad: 'invoer.radius', laag: 'componenten', waarde: "2px" },
  { naam: 'invoer-achtergrond', pad: 'invoer.achtergrond', laag: 'componenten', waarde: "#ffffff" },
  { naam: 'invoer-voorgrond', pad: 'invoer.voorgrond', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'invoer-rand', pad: 'invoer.rand', laag: 'componenten', waarde: "#e3e0d9" },
  { naam: 'invoer-rand-focus', pad: 'invoer.rand-focus', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'invoer-rand-fout', pad: 'invoer.rand-fout', laag: 'componenten', waarde: "#a23a29" },
  { naam: 'invoer-voorbeeld-voorgrond', pad: 'invoer.voorbeeld-voorgrond', laag: 'componenten', waarde: "#9b968d" },
  { naam: 'label-grootte', pad: 'label.grootte', laag: 'componenten', waarde: "0.875rem" },
  { naam: 'label-gewicht', pad: 'label.gewicht', laag: 'componenten', waarde: "500" },
  { naam: 'label-voorgrond', pad: 'label.voorgrond', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'label-optioneel-voorgrond', pad: 'label.optioneel-voorgrond', laag: 'componenten', waarde: "#9b968d" },
  { naam: 'knop-hoogte', pad: 'knop.hoogte', laag: 'componenten', waarde: "3rem" },
  { naam: 'knop-padding-inline', pad: 'knop.padding-inline', laag: 'componenten', waarde: "1.5rem" },
  { naam: 'knop-grootte', pad: 'knop.grootte', laag: 'componenten', waarde: "0.875rem" },
  { naam: 'knop-gewicht', pad: 'knop.gewicht', laag: 'componenten', waarde: "500" },
  { naam: 'knop-spatiering', pad: 'knop.spatiering', laag: 'componenten', waarde: "0.08em" },
  { naam: 'knop-radius', pad: 'knop.radius', laag: 'componenten', waarde: "0" },
  { naam: 'knop-gevuld-achtergrond', pad: 'knop.gevuld-achtergrond', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'knop-gevuld-voorgrond', pad: 'knop.gevuld-voorgrond', laag: 'componenten', waarde: "#ffffff" },
  { naam: 'knop-gevuld-achtergrond-hover', pad: 'knop.gevuld-achtergrond-hover', laag: 'componenten', waarde: "#4a4844" },
  { naam: 'knop-omlijnd-rand', pad: 'knop.omlijnd-rand', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'knop-omlijnd-voorgrond', pad: 'knop.omlijnd-voorgrond', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'navigatie-hoogte', pad: 'navigatie.hoogte', laag: 'componenten', waarde: "5rem" },
  { naam: 'navigatie-grootte', pad: 'navigatie.grootte', laag: 'componenten', waarde: "0.875rem" },
  { naam: 'navigatie-spatiering', pad: 'navigatie.spatiering', laag: 'componenten', waarde: "0.08em" },
  { naam: 'navigatie-voorgrond', pad: 'navigatie.voorgrond', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'navigatie-voorgrond-rust', pad: 'navigatie.voorgrond-rust', laag: 'componenten', waarde: "#4a4844" },
  { naam: 'navigatie-lijn', pad: 'navigatie.lijn', laag: 'componenten', waarde: "#e3e0d9" },
  { naam: 'navigatie-laag', pad: 'navigatie.laag', laag: 'componenten', waarde: "10" },
  { naam: 'link-onderstreping-afstand', pad: 'link.onderstreping-afstand', laag: 'componenten', waarde: "0.15em" },
  { naam: 'link-onderstreping-dikte', pad: 'link.onderstreping-dikte', laag: 'componenten', waarde: "1px" },
  { naam: 'link-onderstreping-kleur', pad: 'link.onderstreping-kleur', laag: 'componenten', waarde: "#e3e0d9" },
  { naam: 'link-onderstreping-kleur-hover', pad: 'link.onderstreping-kleur-hover', laag: 'componenten', waarde: "#1b1a18" },
  { naam: 'pagina-padding', pad: 'pagina.padding', laag: 'componenten', waarde: "1rem" },
  { naam: 'pagina-padding-breed', pad: 'pagina.padding-breed', laag: 'componenten', waarde: "clamp(1.25rem, 0.8rem + 1.8vw, 2.5rem)" },
  { naam: 'pagina-blok-ruimte', pad: 'pagina.blok-ruimte', laag: 'componenten', waarde: "2rem" },
  { naam: 'pagina-blok-ruimte-breed', pad: 'pagina.blok-ruimte-breed', laag: 'componenten', waarde: "1rem" },
  { naam: 'pagina-micro-ruimte', pad: 'pagina.micro-ruimte', laag: 'componenten', waarde: "1.5rem" },
  { naam: 'merk-hoogte', pad: 'merk.hoogte', laag: 'componenten', waarde: "1.75rem" },
  { naam: 'merk-hoogte-breed', pad: 'merk.hoogte-breed', laag: 'componenten', waarde: "2rem" },
  { naam: 'statement-cap', pad: 'statement.cap', laag: 'componenten', waarde: "8.9cqi" },
  { naam: 'statement-cap-breed', pad: 'statement.cap-breed', laag: 'componenten', waarde: "7.4cqi" },
];
